# Generated by Django 3.1.7 on 2021-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210331_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-created'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.RemoveField(
            model_name='testimonio',
            name='testimonioal',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='testigo',
            field=models.CharField(default='Carlos Trejo', max_length=150, verbose_name='Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='text',
            field=models.TextField(verbose_name='Testimonio'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
