# Generated by Django 3.1.7 on 2021-03-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210331_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Red social')),
                ('url', models.CharField(max_length=100, verbose_name='enlace')),
                ('icono', models.CharField(max_length=50, verbose_name='font awesome icon')),
                ('active', models.BooleanField(verbose_name='activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Identificador')),
                ('text', models.TextField(verbose_name='Texto')),
                ('description', models.TextField(verbose_name='Descripción del texto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='testimonio',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
