# Generated by Django 3.1.7 on 2021-03-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210331_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redsocial',
            old_name='icono',
            new_name='icon',
        ),
    ]
