# Generated by Django 3.1.7 on 2021-07-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fix', max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.TextField(default='555555', max_length=10, verbose_name='Teléfono')),
                ('text', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes Contact Point',
                'ordering': ['-created'],
            },
        ),
    ]
